### ISSUE TITLE
Azure DevOps Pipelines running on PR instead of just on merge to main 

### ISSUE THREAD

**Issue by CalvinRodo** [Azure/CanadaPubSecALZ#85]
**Describe the bug**
When I open a new PR in my repo with pipelines configured according to your onboarding guide a job kicks off that insta fails due to missing files. 

I'm okay with it failing my issue is it shouldn't be running my assumption was that these pipelines were only to run when merging to main not when a PR is created. 

**To Reproduce**
1. Follow onboarding guide
2. Create a pipeline using the yml files in the repo
3. Create a PR 
4. watch it fail

**Expected behavior**
I expect it not to kick off a pipeline job when a PR opens

**Screenshots**
![image](https://user-images.githubusercontent.com/87738/143469702-00051d8b-38db-4105-a140-c504c5603e7c.png)

**Comment by SenthuranSivananthan** [comment]
@skeeler can you have a look at this issue?

**Comment by SenthuranSivananthan** [comment]
We can disable the pipelines from running on pull requests via https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#pr-trigger

(last line)

@skeeler, do you think this is enough?

```yaml
trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - policy
      - .pipelines/policy.yml
      - .pipelines/templates/steps/deploy-policy.yml

pr: none

```
